class Storage {
  static Map<String, List<String>> group = {
    "jod gang": [
      'niyam',
      'bhargav',
      'taksh',
      'baldha',
    ],
    "no ashish": [
      'niyam',
      'bhargav',
    ]
  };

  static Set<List<String>> words = {
    ["begin", "start"],
    ["end", "finish"],
    ["happy", "joyful"],
    ["sad", "unhappy"],
    ["smart", "intelligent"],
    ["fast", "quick"],
    ["slow", "sluggish"],
    ["big", "large"],
    ["small", "tiny"],
    ["beautiful", "pretty"],
    ["ugly", "unattractive"],
    ["strong", "powerful"],
    ["weak", "feeble"],
    ["old", "ancient"],
    ["young", "youthful"],
    ["rich", "wealthy"],
    ["poor", "needy"],
    ["easy", "simple"],
    ["hard", "difficult"],
    ["bright", "shiny"],
    ["dark", "dim"],
    ["hot", "warm"],
    ["cold", "cool"],
    ["new", "fresh"],
    ["clean", "clear"],
    ["dirty", "filthy"],
    ["safe", "secure"],
    ["dangerous", "hazardous"],
    ["loud", "noisy"],
    ["quiet", "silent"],
    ["hardworking", "diligent"],
    ["lazy", "indolent"],
    ["funny", "humorous"],
    ["serious", "grave"],
    ["brave", "courageous"],
    ["scared", "afraid"],
    ["friend", "buddy"],
    ["enemy", "foe"],
    ["teacher", "instructor"],
    ["student", "learner"],
    ["doctor", "physician"],
    ["nurse", "caregiver"],
    ["car", "automobile"],
    ["bicycle", "bike"],
    ["train", "rail"],
    ["plane", "airplane"],
    ["book", "novel"],
    ["movie", "film"],
    ["computer", "machine"],
    ["phone", "telephone"],
    ["gift", "present"],
    ["meal", "dinner"],
    ["snack", "treat"],
    ["water", "liquid"],
    ["air", "gas"],
    ["earth", "soil"],
    ["fire", "flame"],
    ["light", "brightness"],
    ["darkness", "shadow"],
    ["truth", "fact"],
    ["lie", "falsehood"],
    ["idea", "concept"],
    ["problem", "issue"],
    ["solution", "answer"],
    ["question", "inquiry"],
    ["debate", "discussion"],
    ["agreement", "consensus"],
    ["disagreement", "conflict"],
    ["love", "affection"],
    ["hate", "dislike"],
    ["hope", "wish"],
    ["fear", "anxiety"],
    ["dream", "fantasy"],
    ["reality", "truth"],
    ["future", "tomorrow"],
    ["past", "history"],
    ["present", "now"],
    ["moment", "instant"],
    ["journey", "trip"],
    ["destination", "goal"],
    ["path", "route"],
    ["travel", "journey"],
    ["visit", "see"],
    ["explore", "discover"],
    ["build", "construct"],
    ["create", "make"],
    ["destroy", "demolish"],
    ["change", "alter"],
    ["improve", "enhance"],
    ["help", "assist"],
    ["fix", "repair"],
    ["sell", "trade"],
    ["buy", "purchase"],
    ["spend", "expend"],
    ["save", "conserve"],
    ["invest", "allocate"],
    ["borrow", "loan"],
    ["lend", "give"],
    ["earn", "receive"],
    ["waste", "misuse"]
  };
}
